services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infotek_books_catalog
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SMS_PILOT_API_KEY=XXXXXXXXXXXXYYYYYYYYYYYYZZZZZZZZXXXXXXXXXXXXYYYYYYYYYYYYZZZZZZZZ
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/v1/books"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
